FROM epitechcontent/epitest-docker:latest

LABEL maintainer="kgtrey1"

COPY ./ /tests

WORKDIR /tests

CMD ["/bin/sh", "-c", "(make tests_run && echo $? && gcovr --exclude test c$* && exit 0) || exit 1"]