##
## EPITECH PROJECT, 2021
## C/C++ CI/CD Workflow for github
## File description:
## dockerfile for tests.
##

FROM epitechcontent/epitest-docker

LABEL maintainer="kgtrey1"

COPY ./ /tests

WORKDIR /tests

CMD ["/bin/sh", "-c", "(make tests_run && echo $? && gcovr --exclude test && exit 0) || exit 1"]